name: usverse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  confetti: ^0.8.0
  cloud_firestore: ^6.1.2
  cryptography: ^2.9.0
  firebase_analytics: ^12.1.2
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  flutter_image_compress: ^2.4.0
  flutter_launcher_icons: ^0.14.4
  flutter_svg: ^2.2.3
  google_sign_in: ^7.2.0
  http: ^1.6.0
  hugeicons: ^1.1.5
  image_picker: ^1.2.1
  intl: ^0.20.2
  mime: ^2.0.0
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_icons/
    - assets/auth_providers/
    - assets/illustrations/
    - assets/logos/
