name: usverse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  confetti: ^0.8.0
  cloud_firestore: ^6.1.2
  firebase_analytics: ^12.1.2
  firebase_auth: ^6.1.4
  firebase_core: ^4.4.0
  flutter_launcher_icons: ^0.14.4
  google_sign_in: ^7.2.0
  http: ^1.6.0
  intl: ^0.20.2
  mime: ^2.0.0
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/app_icons/
    - assets/auth_providers/
    - assets/illustrations/
